apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-external-registry
  labels:
    app: docker-registry
spec:
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30400
      name: registry
  selector:
    app: docker-registry
    release: {{.Release.Name}}
  type: NodePort
