dependencies:
  #  - name: etcd
  #  version: ~0.3.6
  #  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  - name: kafka
    version: ~0.2.11
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  - name: postgresql
    version: ~0.8.5
    repository: https://kubernetes-charts.storage.googleapis.com/
