#imageRegistry: dev-docker-registry.dev.svc.cluster.local 
#imageRegistryPort: 5000
imageRegistry: 127.0.0.1
imageRegistryPort: 30400
etcd:
  Replicas: 1
kafka:
  replicas: 1
  zookeeper:
    servers: 1
postgresql:
  postgresUser: postgres
  postgresPassword: passwordForTesting750

uploadedFilesTopic: "streaming.transcoder.uploaded"
transcodedFilesTopic: "streaming.transcoder.transcoded"

Transcoder:
  MaxMessageSize: "681574400"
  LoggingTopic: "logging.transcoder"
