#imageRegistry: dev-docker-registry.dev.svc.cluster.local 
#imageRegistryPort: 5000
imageRegistry: 127.0.0.1
imageRegistryPort: 30400


# Which kafka topics to use for untranscoded files and
# transcoded files
uploadedFilesTopic: "streaming.transcoder.uploaded"
transcodedFilesTopic: "streaming.transcoder.transcoded"

Transcoder:
  MaxMessageSize: "681574400"
  LoggingTopic: "logging.transcoder"

# Dependency Configuration
etcd:
  Replicas: 1
kafka:
  # Really weird, this line is actually for the schema-registry chart
  #  enabled: false
  replicas: 1
  zookeeper:
    servers: 1
  configurationOverrides:
    offsets.topic.replication.factor: 1
postgresql:
  postgresUser: postgres
  postgresPassword: passwordForTesting750

#schema-registry:
#  kafka.ZookeeperUrl: "{{.Release.Name}}-zookeeper"
