apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: kafka-postgres-connector-deployment
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: kafka-postgres-connector
        spec:
            containers:
            - name: connector
              image: 127.0.0.1:30400/kafka-postgres-connector:latest
              imagePullPolicy: Always
