apiVersion: v1
kind: Pod
metadata:
  name: python-tester
spec:
  containers:
  - name: python
    image: python:3
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
