apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: kafka-postgres-connector-deployment
    labels:
        app: kafka-postgres-connector
spec:
    replicas: 1
    selector:
      matchLabels:
        app: kafka-postgres-connector
    template:
        metadata:
            labels:
                app: kafka-postgres-connector
        spec:
            containers:
            - name: connector
              image: registry.default.svc.cluster.local:5000/kafka-postgres-connector:latest
              imagePullPolicy: Always
