apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: {{.Release.Name}}-kafka-control-center-deployment
    labels:
        app: kafka-control-center
spec:
    replicas: 1
    selector:
      matchLabels:
        app: kafka-control-center
    template:
        metadata:
            labels:
                app: kafka-control-center
        spec:
            containers:
            - name: control-center
              image: confluentinc/cp-control-center 
              imagePullPolicy: Always
              ports:
              - containerPort: 9021
                name: http
                protocol: TCP
              # Normally hangs if it can't find the bootstrap servers
              # so we use a liveness probe to restart
              livenessProbe:
                httpGet:
                  path: /
                  port: 9021
                initialDelaySeconds: 3
                periodSeconds: 3
              env:
                - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
                  value: "{{.Release.Name}}-zookeeper"
                - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
                  value: "{{.Release.Name}}-kafka:9092"
                - name: CONTROL_CENTER_REPLICATION_FACTOR
                  value: "1"
                - name: CONTROL_CENTER_CONNECT_CLUSTER
                  value: "http://{{.Release.Name}}-kafka-postgres-connector:8083"
---
kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-kafka-control-center-svc
spec:
  type: NodePort
  selector:
    app: kafka-control-center
  ports:
  - port: 9021
