apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kafka-ui-deployment
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: ui
        image: sheepkiller/kafka-manager
        ports:
        - containerPort: 9000
        env:
            - name: ZK_HOSTS
              value: "zk-0.zk-svc.default.svc.cluster.local:2181,zk-1.zk-svc.default.svc.cluster.local:2181,zk-2.zk-svc.default.svc.cluster.local:2181"
            - name: APPLICATION_SECRET
              value: "letmein"
---
apiVersion: v1
kind: Service
metadata:
    name: kafka-ui-svc
    labels:
        app: kafka-ui
spec:
    type: NodePort
    ports:
        - port: 9000
    selector:
        app: kafka-ui

